// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpH-pIZH8NzGL0ja5vTrzghoSXEd1THkg',
    appId: '1:523190900965:web:865ff81cfeee1a3695dc0c',
    messagingSenderId: '523190900965',
    projectId: 'mini-habit-tracker-app',
    authDomain: 'mini-habit-tracker-app.firebaseapp.com',
    storageBucket: 'mini-habit-tracker-app.firebasestorage.app',
    measurementId: 'G-J3JLWLGPJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUQSM6Udc3fw2mvcFjnC-DKDw9LxTnUo',
    appId: '1:523190900965:android:16011e38d225e9fb95dc0c',
    messagingSenderId: '523190900965',
    projectId: 'mini-habit-tracker-app',
    storageBucket: 'mini-habit-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCrN7N22KNy6w3PAzuR0gnFgUSFmGlC8',
    appId: '1:523190900965:ios:9ac64aee575a67a995dc0c',
    messagingSenderId: '523190900965',
    projectId: 'mini-habit-tracker-app',
    storageBucket: 'mini-habit-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.miniHabitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjCrN7N22KNy6w3PAzuR0gnFgUSFmGlC8',
    appId: '1:523190900965:ios:9ac64aee575a67a995dc0c',
    messagingSenderId: '523190900965',
    projectId: 'mini-habit-tracker-app',
    storageBucket: 'mini-habit-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.miniHabitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpH-pIZH8NzGL0ja5vTrzghoSXEd1THkg',
    appId: '1:523190900965:web:fb780b326bdeea0e95dc0c',
    messagingSenderId: '523190900965',
    projectId: 'mini-habit-tracker-app',
    authDomain: 'mini-habit-tracker-app.firebaseapp.com',
    storageBucket: 'mini-habit-tracker-app.firebasestorage.app',
    measurementId: 'G-0T4MLWTB30',
  );
}
